.functor luacall_F_F(symbol, float):float
.functor luacall_FF_F(symbol, float, float):float
.functor luacall_F_S(symbol, number):symbol stateful
#define SQUARE(x) @luacall_F_F("mysquare", x)
#define SIN(x) @luacall_F_F("sin", x)
#define MUL(x,y) @luacall_FF_F("*", x, y)
#define LUASTRING(x) @luacall_F_S("tostring", x)
#define HELLO(x) @luacall_F_S("hello", x)
.decl test(x : float, n : float)
test(x, SQUARE(x)) :- x = 3.
test(x, SQUARE(x)) :- x = 5.
//test(x, MUL(x,x+2)) :- x = 5.

.decl test2(x : number, n : symbol)
test2(x, HELLO(x)) :- x = 3.
.output test(IO=stdout)
.output test2(IO=stdout)